# Compose file: final_drive_to_table.yml    # Drive to the pick table.

services:

  drive_to_table:
    extends:
      file: ../../../docker/.compose_templates.yml
      service: .tiago_sim
      
    command:
          - bash
          - -c
          - |
            
            source /opt/ros/humble/setup.bash
            source install/setup.bash
            ros2 launch rwu_tiago_bringup sim_robocup_2023.launch.py is_public_sim:=True x:=-3.0 y:=-1.0 yaw:=1.6 navigation:=True slam:=False map_path:=/maps/myfirstmap.yaml &          

            
            ros2 run gazebo_ros spawn_entity.py -entity door -database counter -x -3.0 -y 0.0 -z 0 -Y 0 

            tail -f /dev/null




# my workspace
# commands and colcon build
  nb-246830_workspace:
    extends:
      file: ../../../docker/.compose_templates.yml
      service: .custom_image
    command: 
      - bash
      - -c
      - |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        sleep 17
        ros2 run clean_the_table drive_to_table &

        tail -f /dev/null

