# Example command:
#   Humble on a NVIDIA system:
#   DOCKER_IMAGE=humble-humble-tutorial-source docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source compose run cpu
#DOCKER_IMAGE=main-rolling-tutorial-source docker compose -f moveit_demo.yml run --rm --name moveit2_container gpu

services:
  cpu:
    image: moveit/moveit2:${DOCKER_IMAGE}
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ../stage_6:/root/ws_moveit/src # mounting
      
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
  gpu:
    image: moveit/moveit2:${DOCKER_IMAGE}
    container_name: moveit2_container    
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      #- ../stage_6:/root/ws_moveit/src/mount # mounting
      - ${IKI_WORKSPACE_2026}/ros2_ws:/root/ws_moveit
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      COLCON_CURRENT_PREFIX: /root/ros2_ws/install  # Explicitly set
